version: '2'
services:
  jfrog:
    image: docker.bintray.io/jfrog/artifactory-oss
    volumes:
      - ./jfrog/artifactory:/var/opt/jfrog/artifactory
      - ./assets/artifactory.config.xml:/var/opt/jfrog/artifactory/etc/artifactory.config.xml
    ports:
      - "8081:8081"

