version: '2'
services:
  database:
    image: postgres:9.6.1
    env_file:
      - .postgres.env
    ports:
      - "5432"
  opennms_build:
    image: opennms/build-env
    env_file:
      - .opennms.env
      - .postgres.env
    depends_on:
      - database
    volumes:
      - ./opennms/target/opennms:/opt/opennms
      - ./assets/settings.xml:/root/.m2/settings.xml
    command: [ "/opennms.sh", "-t" ]
    ports:
      - "8980"
      - "18980"
      - "1099"
      - "8101"
      - "8001"
      - "61616"
      - "5817"
      - "162/udp"
  jfrog:
    image: docker.bintray.io/jfrog/artifactory-oss
    volumes:
      - /var/opt/jfrog/artifactory:/var/opt/jfrog/artifactory
      - ./assets/artifactory.config.latest:/var/opt/jfrog/artifactory/etc/artifactory.config.latest
    ports:
      - "8081"